### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by t2** [clover/remote-pay-cloud-api#3]
The `preinstall` and `postversion` scripts will not run on Windows by default. Any plans to support it?

**Comment by mike-clover-com** [comment]
Hi Trent.  At this time we do not have plans for windows support on the scripts.  However, not running these scripts should have little impact on your code.  The preinstall script generates documentation using jsdoc, and the postversion script is currently a stub (and as such will be removed now that I noticed this).

**Comment by t2** [comment]
Thanks @mike-clover-com! I went ahead and ignored scripts and all is working.
