### ISSUE TITLE
Uncaught ReferenceError: AppExclusionType is not defined

### ISSUE THREAD

**Issue by shahzib111** [clover/remote-pay-cloud-api#48]
I recently upgraded from angular 7 to angular 10 and for some reason i am getting the following error

Uncaught ReferenceError: AppExclusionType is not defined at Object.gGmd (AppExclusionType.js:12) at __webpack_require__ (bootstrap:79) at Object.WpDk (index.js:10) at __webpack_require__ (bootstrap:79) at Object.wvk5 (index.js:8) at __webpack_require__ (bootstrap:79) at Object.qk9L (index.js:2) at __webpack_require__ (bootstrap:79) at Module.VjSG (main.js:5067) at __webpack_require__ (bootstrap:79)

I found that after the upgrade, a bunch of declarations in the node modules that are generated from this are not declared, AppExclusionType being one of the many. adding a 'var' or 'const' infront of it fixed the problem. The same issue was on multiple other enums and classes have the same issue. Another one is payments.

to help clarify the issue, one such enum that caused the issue was 
`AppExclusionType = {
  ALL : "ALL",
  MARKET : "MARKET",
  SEARCH : "SEARCH",
  INSTALL : "INSTALL"
};`

and the error was fixed by adding var infront of it as shown below:
`var AppExclusionType = {
  ALL : "ALL",
  MARKET : "MARKET",
  SEARCH : "SEARCH",
  INSTALL : "INSTALL"
};`

**Comment by david-clover-com** [comment]
These model classes are generated.  I will create an issue on our end to fix the generator to build strict mode compatible code.  I am a bit curious why AppExclusionType is being included in your bundle as I don't think that is used anywhere.  Are you only importing remote-pay-cloud or are you importing remote-pay-cloud-api somewhere?  It would be helpful to see a minimal example with steps on reproducing the issue.

**Comment by shahzib111** [comment]
I am actually using remote-pay-cloud-api  and the error is coming from that library. can you please create a ticket for strict mode on that repo rather then this one as remote-pay-cloud works fine and it was remote-pay-cloud-api  that was failing.

**Comment by david-clover-com** [comment]
Hi @shahzib111, this is remote-pay-cloud-api.   Please see my previous questions:  `I am a bit curious why AppExclusionType is being included in your bundle as I don't think that is used anywhere. Are you only importing remote-pay-cloud or are you importing remote-pay-cloud-api somewhere? It would be helpful to see a minimal example with steps on reproducing the issue.`

**Comment by david-clover-com** [comment]
@shahzib111 fixed in 4.0.4 of remote-pay-cloud-api and 4.0.5 of remote-pay-cloud.
